version: "3"
services:
  lms-fe:
    container_name: lms-fe
    build:
      context: ../manazel-alabrar-fe
      dockerfile: Dockerfile
    environment:
      API_URL: https://lms-be.manazel-alabrar.com
    networks:
      - letsencrypt-docker-compose

  lms-be:
    container_name: lms-be
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: lms-be:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: lms-beDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public:/opt/app/public
    networks:
      - lms-be
      - letsencrypt-docker-compose
    depends_on:
      - lms-beDB
  lms-beDB:
    container_name: lms-beDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/ # if you want to use a bind folder
    networks:
      - lms-be
  pgadmin:
    container_name: pgadmin_container_2
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - lms-be
      - letsencrypt-docker-compose
    restart: unless-stopped

networks:
  lms-be:
    name: Lms-be
    driver: bridge
  letsencrypt-docker-compose:
    name: letsencrypt-docker-compose_default
    external: true
